### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by HBU-Lin-Li** [Yunfan-Li/Contrastive-Clustering#11]
Hi,
when i test the 'ImageNet-dogs'，i get the error“IndexError: index 14 is out of bounds for axis 0 with size 1”, and i print the cost_matrix in 'evaluation.py',i only get [[0.]].
Is it because I trained less epoch?

Thanks.

**Comment by Yunfan-Li** [comment]
Have you checked the dimension of CCH?

**Comment by HBU-Lin-Li** [comment]
I have set thd dimension of CCH with class_num

**Comment by HBU-Lin-Li** [comment]
After 20 epochs, i tested 'ImageNet-dogs',i print len(indices) and i get 1,but 'CIFAR10/100' is True

**Comment by HBU-Lin-Li** [comment]
``
![Uploading image.png…]()

**Comment by Yunfan-Li** [comment]
Perhaps it is because the file organization of ImageNet-dogs is wrong. You may check the ground truth labels and see if contains 0-14.

**Comment by HBU-Lin-Li** [comment]
I get the datasets from http://vision.stanford.edu/aditya86/ImageNetDogs/,it includes images and annotations .
How  do i deal with?
Thanks.

**Comment by Yunfan-Li** [comment]
I command using ImageFolder following the instructions in https://pytorch.org/vision/stable/datasets.html#imagefolder.

**Comment by Yunfan-Li** [comment]
The dataset you downloaded seems to be inconsistent with the one used in the paper. In our experiments, the ImageNet-dogs data consists of 15 subclasses of the original Imagenet dataset, the indices of which are given in /datasets/ImageNet-dogs.txt.

**Comment by HBU-Lin-Li** [comment]
I have already corrected the data consists of 15subclasses, and then I need to  merge 'images' with 'annotations'？

**Comment by Yunfan-Li** [comment]
Please follow the instructions in https://pytorch.org/vision/stable/datasets.html#imagefolder and arrange images of different classes in different subfolders.

**Comment by HBU-Lin-Li** [comment]
Now，i followed the indices and arrange images of different classes in in different subfolders with the indices,but i only get 2436 images...

**Comment by Yunfan-Li** [comment]
Each class contains 1300 images and thus there should be 19500 images in total.

**Comment by HBU-Lin-Li** [comment]
The datasets with 120 classes downloaded from  http://vision.stanford.edu/aditya86/ImageNetDogs, now, I process this dataset according to the index, but per class only has more than 100.

**Comment by Yunfan-Li** [comment]
Perhaps you need to download the ImageNet dataset and select its 15 subclasses.

**Comment by HBU-Lin-Li** [comment]
Can i have your QQ? 
My qq is 631681821,thanks.
I need your help...
