### ISSUE TITLE
More details on conclusion

### ISSUE THREAD

**Issue by sramakrishnan247** [Yunfan-Li/Contrastive-Clustering#17]
Hey!
The paper is extremely well written but could you give some more info on the following part -

_The proposed CC shows its promising performance in clustering. In the future, we plan to extend it to other tasks and applications such as semi-supervised learning and transfer learning._

This was mentioned in the conclusion. 
Is this a new area of research, or are there applications other than clustering that can be done with this existing repository? 
Can you please give some more insights about this part?

**Comment by Yunfan-Li** [comment]
Thanks for your interest! What you mentioned above is our intuitive plan on extending our method in the future. This repository is used for image clustering or unsupervised representation learning.
