### ISSUE TITLE
Questions about multi-GPU training

### ISSUE THREAD

**Issue by Allfu** [Yunfan-Li/Contrastive-Clustering#18]
Thanks for sharing such an excellent work：
Are there any plans to provide multi-GPU training scripts?
I would be very grateful if I could provide it！
thanks!

**Comment by Yunfan-Li** [comment]
We didn't implement a multi-GPU version of the training scripts. However, since this method is based on SimCLR, I recommend you refer to the multi-GPU code of SimCLR (e.g, https://github.com/Spijkervet/SimCLR) and modify the scripts accordingly.

**Comment by Allfu** [comment]
ok ,got it,thanks!
