### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by AndyandViky** [Yunfan-Li/Contrastive-Clustering#2]
This idea is very similar to this paper 'Deep Robust Clustering by Contrastive Learning'.

**Comment by Yunfan-Li** [comment]
Hi, we noticed that there are at least three independent works of using contrastive learning for clustering - our "Contrastive Clustering" (AAAI2021, arXiv:2009.09687), the mentioned "Deep Robust Clustering by Contrastive Learning" [1] (arXiv:2008.03030), and another one "Learning Representations by Contrasting Clusters While Bootstrapping Instances" [2] (submitted to ICLR 2021). During the AAAI rebuttal phase, we noticed [1] and cited it in our camera ready, and we saw [2] several days ago.  

The three works share a similar idea of conducting contrastive learning at both the instance- and cluster-level and are proposed within the same period, which proves the value and effectiveness of this idea.

Among the three works, we would like to highlight (one major difference with these works) that our story explicitly starts with the idea of "label is representation'' and we accordingly proposed that contrastive learning could be applied to the row and column space of data. As a result, clustering can be achieved in an online manner. Note that the advantage of online clustering is also pointed in our work only. Besides, we found that our method is remarkably superior to [1,2] even they own a similar idea. For example, our method achieves 0.705 NMI on CIFAR-10 compared with 0.621 by [1] and 0.630 by [2].

Anyway, these three independent works show the value of using contrastive learning for clustering. And if the authors of [1-2] see this message, we would be highly encouraged and grateful if you could cite our work, just like we did.

**Comment by AndyandViky** [comment]
Thank you for your comment. I later found the differences in these papers. The idea of 'label is representation' is novel.
