### ISSUE TITLE
Could you please offer your code of t-SNE?

### ISSUE THREAD

**Issue by zbw0329** [Yunfan-Li/Contrastive-Clustering#23]
Hi,thanks for your excellent CC.
I want to visualize the clustering result,could you please release your code of t-SNE?

**Comment by Yunfan-Li** [comment]
Hi, you may refer to the previous issue #14. And here is a simple example of t-SNE plot.
`
def tSNE(X, Y):
    from sklearn.manifold import TSNE
    X_embedded = TSNE(n_components=2).fit_transform(X)
    plt.figure()
    plt.scatter(X_embedded[:, 0], X_embedded[:, 1], c=Y)
    plt.savefig("./tSNE.png")
    plt.close()
`
For other color choices, you could take a look at `matplotlib.colors`.

**Comment by zbw0329** [comment]
Thanks for your help!
