### ISSUE TITLE
关于对比算法的实现

### ISSUE THREAD

**Issue by zbw0329** [Yunfan-Li/Contrastive-Clustering#26]
您好，我对您CC的研究非常感兴趣。
我想问一下您论文中实验部分，您的对比算法K-means和SC是如何实现的？
能否简要介绍一下您对比算法都是如何实现的？我想要在自己的数据集上复现您的对比实验

**Comment by zbw0329** [comment]
您好，我想问一下imagenet-10和imagenet-dogs下的目录应该是怎样排布的？

**Comment by Yunfan-Li** [comment]
您好，直接使用Pytorch提供的ImageFolder类就可以了，具体地可以参考 #10

**Comment by zbw0329** [comment]
您好，我对cc进行了一些修改，添加了一个投影头，然后在imagenet-10上训练，在使用cluster.py进行评估的时候得到了如下的报错
![1638888975(1)](https://user-images.githubusercontent.com/50667397/145052318-7b539665-e1d8-4672-90fc-b792ff3c30cd.png)
在训练过程中没有报错，请问您知道为什么出现这样的报错吗？

**Comment by Yunfan-Li** [comment]
应该是目标聚类个数和ground truth不一致，您可能需要尝试修改ACC的计算方式。

**Comment by zbw0329** [comment]
我发现是因为我读的label全是0，所以报错，还在排查是为什么，感谢您的帮助

**Comment by zbw0329** [comment]
解决了，原因是我在放数据集的时候多加了一层文件夹train,导致在运行clusetr.py读不到数据进行验证，所以读的标签全是0
感谢您的研究工作以及您提供的帮助
