### ISSUE TITLE
关于您提供的预训练模型中的问题

### ISSUE THREAD

**Issue by zbw0329** [Yunfan-Li/Contrastive-Clustering#27]
您好，感谢您出色的研究工作。
我想问一下为什么读取您代码中提供的checkpoint的时候，显示没有optimizer的参数？

**Comment by Yunfan-Li** [comment]
最开始有几个模型在跑的时候忘记存optimizer了😂

**Comment by zbw0329** [comment]
请问能否更新一下完整的checkpoint呢？

**Comment by Yunfan-Li** [comment]
优化器和训练的参数在config文件中已经完整给出了，您可以重新训练一个模型。

**Comment by zbw0329** [comment]
谢谢您的帮助
