### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by GlancerZ** [Yunfan-Li/Contrastive-Clustering#32]
您好，有两个问题。
1、每个epoch都需要重新进行不同数据增强吗，每次的数据增强方式一样吗？
2、我自己的数据集比较小，只有数百个，但是维度接近一万，因为不是图像数据，我采用在每一个epoch加入两个不同噪声的方式构建正样本对，但是训练过程很不稳定，请问有什么改进的办法呢？
谢谢！

**Comment by Yunfan-Li** [comment]
1、每个epoch数据的增广都是从transform这个增广池子里面随机选择的
2、数据增广通常需要针对不同类型的数据进行定制，通用的增广可参考virtual adversarial training
