### ISSUE TITLE
resnet模型参数的疑问

### ISSUE THREAD

**Issue by zkk995** [Yunfan-Li/Contrastive-Clustering#45]
你好，比较细致的学习的你代码。 下面的问题请教一下：

看train.py中，优化器只优化了network的参数， resnet模型的参数不包含在内， 是不是有问题？
因为往前看 resnet.get_resnet函数 调用了 modules目录的代码， 并不是一个预先训练好的模型。 

```python
    res = resnet.get_resnet(args.resnet)
    model = network.Network(res, args.feature_dim, class_num)
    model = model.to('cuda')
    # optimizer / loss
    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
```

**Comment by Yunfan-Li** [comment]
你好，你可以打印一下model.parameters()，里面应该包含resnet的参数。另外聚类任务里面一般不使用有监督预训练的模型。

**Comment by zkk995** [comment]
> 你好，你可以打印一下model.parameters()，里面应该包含resnet的参数。另外聚类任务里面一般不使用有监督预训练的模型。

非常感谢及时回复～，学习到了 👍    用 model.named_parameters() 看到。
