### ISSUE TITLE
关于x_i和x_j是怎么得到的

### ISSUE THREAD

**Issue by Youngmits** [Yunfan-Li/Contrastive-Clustering#51]
你好，我查看了代码，但是没有找到代码中定义x_i和x_j的相关代码，不知道是不是我没有找到。请问是怎么得到x_i和x_j的呢

**Comment by Yunfan-Li** [comment]
通过数据增广获得

**Comment by Yunfan-Li** [comment]
[transform.py](https://github.com/Yunfan-Li/Contrastive-Clustering/blob/main/modules/transform.py)
