### ISSUE TITLE
当数据量较少时可以获得不错的聚类效果，但是当数据量增大时训练到100轮之后聚类结果则会逐渐下降

### ISSUE THREAD

**Issue by coreeey** [Yunfan-Li/Contrastive-Clustering#52]
您好，我正在使用对比聚类进行一个四分类实验，当每类只有250张图片时，聚类acc可以到到70%。但是当每类增加到2000张时，网络每次训练到100轮（此时acc 50%左右）之后acc就会逐渐下降，最终稳定在35左右，通过混淆矩阵可以观察到此时并没有出现全分为一类的情况。然而，我使用250张图片得到的模型对每类2000张的数据进行聚类时，acc却有60%，尝试修改了学习率，模型以及loss权重仍然无法解决这个问题，请问您有遇到过类似的问题嘛？或者您对这个问题有什么特殊的见解嘛？

**Comment by Yunfan-Li** [comment]
您好，我之前没有碰到过这种情况，比如CIFAR-10每个类应该是6000张图片，模型也能够正常训练。针对您说的这种情况，您有没有尝试过对于训练了100轮（此时acc 50%左右）和最终稳定在35左右的模型提取到的特征分别用tSNE可视化看下呢？观察一下特征空间是怎么变化的导致性能大幅下降。另外也可以测试一下2000张训练的模型对于250张图片的聚类精度是否仍能达到70%。希望对您有帮助。

**Comment by coreeey** [comment]
感谢您的回复，我这里再深入研究一下。
