### ISSUE TITLE
pytorch version and torchvision version are not compatib

### ISSUE THREAD

**Issue by DEPhantom** [Yunfan-Li/Contrastive-Clustering#54]
If torchvision version is 0.8.1
the pytorch version required 1.7.0
Is there any error in your dependency?

**Comment by Yunfan-Li** [comment]
The version of dependency is copied from our environment. Anyway, I guess the code still works with higher versions of the packages.

**Comment by DEPhantom** [comment]
I have installed PyTorch 1.7.0 and torchvision 0.8.1. It works now, thank you.
