### ISSUE TITLE
One discussion on the number of clusters

### ISSUE THREAD

**Issue by MongoTap** [Yunfan-Li/Contrastive-Clustering#55]
场景：representation learning using unsupervised clustering （task不是classification）

您好，如果dataset事先没有label，无法事先得知M，即cluster num，有什么其他办法可以优雅地确定呢？

**Comment by Yunfan-Li** [comment]
您好，对于表示学习来说，设定一个相对大的cluster number通常情况下就可以了，如果想要较为精确的推断聚类个数，可以去参考一些专门研究类别个数发现的工作，例如https://github.com/BGU-CS-VIL/DeepDPM

**Comment by MongoTap** [comment]
好的，非常感谢！
