### ISSUE TITLE
Plans for release supplementary materials

### ISSUE THREAD

**Issue by qzhang5217** [Yunfan-Li/Contrastive-Clustering#6]
Hello, you have mentioned that there are some experiments in your supplementary material. Do you have any plan to release the supplementary material. Thanks for your reply.

**Comment by qzhang5217** [comment]
Thanks for your reply. We want to know how the setting of the dimensionality of ICH (cluster num) influence the results  and how you choose the specific value across different datasets.

**Comment by Yunfan-Li** [comment]
The dimensionality of CCH is always the same as the cluster number (known in prior for different datasets), in order to make cluster assignments. Thus, it is not a hyper-parameter.

**Comment by qzhang5217** [comment]
Thanks for you reply. I initially thought that as an unsupervised problem, it is reasonable that a priori, including cluster number, is not known. But I also accept your explanation.

**Comment by Yunfan-Li** [comment]
The estimation of the underlying cluster number is a challenging problem in clustering. It remains to be solved in future works.

**Comment by qzhang5217** [comment]
Thanks for your reply. Look forward to your future works.
