### ISSUE TITLE
用CC预处理数据并提取特征以用于下游任务

### ISSUE THREAD

**Issue by sagechang2020** [Yunfan-Li/Contrastive-Clustering#61]
作者您好！

非常感谢您工作的开源。
目前我正在考虑将您的CC作为数据集的预处理手段，提取stl10、cifar10的特征表示以用于下游任务。
可否请问，您认为“ICH的输出（即instance_projector输出的z）”和“backbone的输出（即resnet输出的h）”，哪个更适合作为数据的新特征表示？

非常感谢！

**Comment by sagechang2020** [comment]
> 作者您好！
> 
> 非常感谢您工作的开源。 目前我正在考虑将您的CC作为数据集的预处理手段，提取stl10、cifar10的特征表示以用于下游任务。 可否请问，您认为“ICH的输出（即instance_projector输出的z）”和“backbone的输出（即resnet输出的h）”，哪个更适合作为数据的新特征表示？
> 
> 非常感谢！

（注：这里“ICH的输出”和“backbone的输出”均使用的是完成1000个epoch的训练之后的模型

**Comment by Yunfan-Li** [comment]
您好，这取决于您的下游任务，表示h相较z具有更多的信息，而z则通常更具有判别性，可以参考SimCLR的实验结果。

**Comment by sagechang2020** [comment]
您好！

非常感谢您的回复！
经我之前简单的尝试，情况确实如此，非常感谢帮助！

祝好！
