### ISSUE TITLE
Why do your result in  paper_with paper dimension Disappeared？

### ISSUE THREAD

**Issue by miziha-zp** [Yunfan-Li/Contrastive-Clustering#8]
Why do your result in  [paper_with_paper](https://paperswithcode.com/sota/image-clustering-on-cifar-10) Disappear？

**Comment by Yunfan-Li** [comment]
> Why do your result in paper_with paper dimension Disappeared？

Sorry, I don't quite understand your question.

**Comment by miziha-zp** [comment]
> > Why do your result in paper_with paper dimension Disappeared？
> 
> Sorry, I don't quite understand your question.

sorry for my poor englist...

**Comment by Yunfan-Li** [comment]
Thank you for pointing out that! It seems the results on some datasets are missed. I have just updated the result on the [paper-with-code page](https://paperswithcode.com/paper/contrastive-clustering).
