### ISSUE TITLE
loss function

### ISSUE THREAD

**Issue by wjczf123** [Yunfan-Li/Contrastive-Clustering#9]
Is there no I{j $\neq$ i} (same as SimCLR) in the loss function (2) and (5)?

**Comment by Yunfan-Li** [comment]
In the code implementation, we exclude the pair j=i in the denominator. But in the paper, we didn't exclude that term for simplicity, since it always equals 1.0.

**Comment by wjczf123** [comment]
OK. Thank you very much!

**Comment by LinNan1** [comment]
> In the code implementation, we exclude the pair j=i in the denominator. But in the paper, we didn't exclude that term for simplicity, since it always equals 1.0.

But why does the pair j=i in the denominator always equal 1.0 ?

**Comment by Yunfan-Li** [comment]
The cosine similarity between each sample and itself is 1.0
